baseURL = "https://www.jonasskanoy.xyz"
title = "Jonas B. Skånøy"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "bw"
pygmentsCodeFences = false
pygmentsCodeFencesGuessSyntax = false

# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Jonas B. Skånøy"
info = ["Philosophy", "Tech"]
description = "Jonas Skånøy's personal website"
keywords = "blog,personal"
avatarURL = "images/profile.jpg"
#gravatar = "john.doe@example.com"
	
favicon_32 = "images/profile.jpg"
favicon_16 = "images/profile.jpg"

since = 2022

# Enable the right to left mode.
rtl = false

colorScheme = "auto"
hideColorSchemeToggle = true
	
# Add extra CSS files to the website. ["css/extra-style.css"]
# customCSS = []

# Add extra SCSS files to the website. ["scss/extra-style.scss"]
# customSCSS = []
	
# Add extra JS files to the website. ["js/extra-script.js"]
# customJS = []

# Adds support for Twemoji
enableTwemoji = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/jonasskanoy/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 2
url = "https://www.jonasskanoy.xyz/posts/index.xml"
rel = "alternate"
type = "application/rss+xml"

# Menu links
[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[menu.main]]
name = "Contact me"
weight = 3
url = "contact/"
